# Configuration for the-welcome-bot - https://github.com/bash-bot/the-welcome-bot

# Message for a new user who open an issue
issueOpen: >
  Thanks and congrats for opening your very first issue in this project. Horray!
  A project manager will get back to you shortly! In the meantime, why don't you join our discord server?

# Message for a new user who comments on an issue
issueComment: >
  This appears to be your very first comment on an issue! How awesome! Make sure your coments are relevant to the issue!

# Default message for a new user
welcomeMessage: >
  Hello World!
